#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: nfs-client-provisioner
#---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: home.swinney.io/nfs
            - name: NFS_SERVER
              value: nas-media 
            - name: NFS_PATH
              value: /mnt/user/docker-appdata 
      volumes:
        - name: nfs-client-root
          nfs:
            server: nas-media 
            path: /mnt/user/docker-appdata 
