apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:latest
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector: 
    workload: mldl

