apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  labels:
    app: prometheus-server
  name: prometheus-data 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
