serviceType: LoadBalancer 
externalTrafficPolicy: Cluster
replicas: 1
debug:
  enabled: false
ssl:
  enabled: true
  enforced: true
acme:
  enabled: true
  email: ben@swinney.io
  staging: false
  logging: true
  challengeType: http-01
  persistence:
    enabled: true
    annotations: {}
    accessMode: ReadWriteOnce
    size: 1Gi
dashboard:
  enabled: true
  domain: traefik.swinney.io 
  service:
    annotations:
      kubernetes.io/ingress.class: traefik
  auth:
    basic:
      admin: $apr1$xcflcQHh$Qvfwl4IUOgryLU0ym1JfW/ 
gzip:
  enabled: true
accessLogs:
  enabled: false
  ## Path to the access logs file. If not provided, Traefik defaults it to stdout.
  # filePath: ""
  format: common  # choices are: common, json
rbac:
  enabled: true
## Enable the /metrics endpoint, for now only supports prometheus
## set to true to enable metric collection by prometheus

deployment:
  hostPort:
    httpEnabled: true
    httpsEnabled: true
